spring:
  application:
    name: flowstate-api
  jpa:
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
  data:
    redis:
      repositories:
        enabled: false
springdoc:
  swagger-ui:
    use-root-path: true
jwt:
  private-key: classpath:jwt/app.key
  public-key: classpath:jwt/app.pub
  access-token-ttl: 5m
  refresh-token-ttl: 1d

otp:
  email-verification:
    cache-prefix: otp:email-verification:%s
    ttl: 5m
    length: 6